apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-data
spec: 
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  hostPath:
    path: /data/nfs 
