apiVersion: triggers.tekton.dev/v1beta1 
kind: TriggerTemplate
metadata:
  name: fiops-order-pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
      default: tekton-pipeline
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: rd-pipeline-run-$(uid)
        namespace: $(tt.params.namespace)
      spec:
        serviceAccountName: default
        params: 
        - name: revision
          value: $(tt.params.gitrevision)
        - name: repo-url
          value: $(tt.params.gitrepositoryurl)
        pipelineRef:
          name: fiops-order-pipeline 
        workspaces:
        - name: shared-workspace
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              storageClassName: nfs-client 
              resources:
                requests:
                  storage: 1Gi
        - name: dockerhub-auth
          secret:
            secretName: docker-credential
        - name: git-credentials
          secret:
            secretName: git-credentials
