apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: '2024-03-05T09:18:22Z'
  generation: 1
  name: fiops-pipeline-template
  namespace: default
spec:
  params:
    - default: master
      description: The git revision
      name: gitrevision
    - description: The git repository url
      name: gitrepositoryurl
    - default: tekton-pipeline
      description: The namespace to create the resources
      name: namespace
    - name: application
      description: The application needs to be triggered
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.application)-pipeline-run-
        namespace: $(tt.params.namespace)
      spec:
        params:
          - name: revision
            value: $(tt.params.gitrevision)
          - name: repo-url
            value: $(tt.params.gitrepositoryurl)
        pipelineRef:
          name: $(tt.params.application)-pipeline
        serviceAccountName: default
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: nfs-client
          - name: dockerhub-auth
            secret:
              secretName: docker-credential
          - name: git-credentials
            secret:
              secretName: git-credentials
