apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: k8s-deploy
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: CLI
    tekton.dev/tags: search
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    This task performs curl operation to transfer data from internet.

  params:
  - name: url
    description: URL to curl'ed
    type: string
  - name: image-url
    type: string
  - name: curl-image
    description: option of curl image
    type: string
    default: "registry.cn-beijing.aliyuncs.com/fpf_devops/curlimages/curl:7.72.0@sha256:bd5bbd35f89b867c1dccbc84b8be52f3f74dea20b46c5fe0db3780e040afcb6f" #tag: 7.72.0
  steps:
  - name: curl
    image: "$(params.curl-image)"
    command: [curl]
    args:
    - "-s"
    - "-i"
    - "-v"
    - "-X"
    - "POST"
    - "-H"
    - 'Content-Type: application/json'
    - "-d"
    - '{ "app_name": "fiops-bkcmdb", "env": "dev", "artifact_url": "$(params.image-url)" }'
    - "$(params.url)"
