apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go1.19-build
  labels:
    app.kubernetes.io/version: "0.3"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/displayName: "golang build"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This Task is Golang task to build Go projects.
  params:
  - name: workbase
    description: base package to build in
  - name: packages
    description: "packages to build (default: ./cmd/...)"
    default: "./cmd/..."
  - name: version
    description: golang version to use for builds
    default: "latest"
  - name: flags
    description: flags to use for the test command
    default: -v
  - name: GOOS
    description: "running program's operating system target"
    default: linux
  - name: GOARCH
    description: "running program's architecture target"
    default: amd64
  - name: GO111MODULE
    description: "value of module support"
    default: auto
  - name: GOCACHE
    description: "Go caching directory path"
    default: ""
  - name: GOMODCACHE
    description: "Go mod caching directory path"
    default: ""
  - name: CGO_ENABLED
    description: "Toggle cgo tool during Go build. Use value '0' to disable cgo (for static builds)."
    default: "0"
  - name: GOSUMDB
    description: "Go checksum database url. Use value 'off' to disable checksum validation."
    default: ""
  - name: GOPROXY
    default: "https://repo.cicc.com.cn/artifactory/public-go-virtual/"
  workspaces:
  - name: source
  results:
    - name: version
    - name: timestamp
  steps:
  - name: build
    image: repo.cicc.com.cn/public-docker-virtual/golang:1.19-rc
    workingDir: $(workspaces.source.path)
    script: |
      go version
      cd $(params.workbase)
      IMAGE_VERSION="$(cat VERSION)"
      printf "%s" "${IMAGE_VERSION}" > "$(results.version.path)"
      go build $(params.flags) $(params.packages)
      timestamp=$(date +%Y%m%d%H%M%S)
      printf "%s" "${timestamp}" > "$(results.timestamp.path)"
    volumeMounts:
      - name: host-time
        mountPath: /etc/localtime 
    env:
    - name: GOOS
      value: "$(params.GOOS)"
    - name: GOARCH
      value: "$(params.GOARCH)"
    - name: GO111MODULE
      value: "$(params.GO111MODULE)"
    - name: GOCACHE
      value: "$(params.GOCACHE)"
    - name: GOMODCACHE
      value: "$(params.GOMODCACHE)"
    - name: CGO_ENABLED
      value: "$(params.CGO_ENABLED)"
    - name: GOSUMDB
      value: "$(params.GOSUMDB)"
    - name: GOPROXY
      value: "$(params.GOPROXY)"
  volumes: 
    - name: host-time
      hostPath:
        path: /etc/localtime
