apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
 generateName: lizardcd-server-agent-run-
spec:
  pipelineRef:
    name: lizardcd-agent-pipeline
  workspaces:
  #  - name: maven-settings
  #    configMap:
  #      name: custom-maven-settings
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteMany
          storageClassName: nfs-client
          resources:
            requests:
              storage: 1Gi
    - name: dockerhub-auth
      secret:
        secretName: docker-credential
    - name: git-credentials
      secret:
        secretName: git-credentials
  params:
  - name: revision
    value: main
 # taskRunSpecs:
 #   - pipelineTaskName: yq-replace
 #     taskPodTemplate:
 #       securityContext:
 #         runAsUser: 0
