apiVersion: v1
kind: Service
metadata:
  name: el-fiops-k8s-eventlistener
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-listener
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: fiops-k8s-pipeline-eventlistener
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
